"""Initial delete releation user-wish

Revision ID: 1f9ebbf54ad4
Revises: c47da6fc0640
Create Date: 2024-04-01 23:22:50.672620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9ebbf54ad4'
down_revision: Union[str, None] = 'c47da6fc0640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
