"""promocode-duration

Revision ID: 27ee4220d562
Revises: 36a56656036f
Create Date: 2024-08-27 21:31:01.818360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ee4220d562'
down_revision: Union[str, None] = '36a56656036f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo', sa.Column('premium_duration', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('time_premium', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_premium')
    op.drop_column('promo', 'premium_duration')
    # ### end Alembic commands ###
