"""promocode

Revision ID: 52c7c9666403
Revises: fcaf359273e2
Create Date: 2024-08-26 22:11:48.275403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c7c9666403'
down_revision: Union[str, None] = 'fcaf359273e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promo_code', table_name='promo')
    op.create_index(op.f('ix_promo_code'), 'promo', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_code'), table_name='promo')
    op.create_index('ix_promo_code', 'promo', ['code'], unique=False)
    # ### end Alembic commands ###
