"""Initial delete releation user-wish

Revision ID: 68c05d092d03
Revises: 1f9ebbf54ad4
Create Date: 2024-04-01 23:23:49.521320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c05d092d03'
down_revision: Union[str, None] = '1f9ebbf54ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wishes_owner_id_fkey', 'wishes', type_='foreignkey')
    op.drop_column('wishes', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('wishes_owner_id_fkey', 'wishes', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
