"""wishhistory

Revision ID: 80b6543874dd
Revises: 2c4126b84c15
Create Date: 2024-07-25 22:44:33.608778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b6543874dd'
down_revision: Union[str, None] = '2c4126b84c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_histories', sa.Column('title', sa.String(), nullable=False))
    op.create_index(op.f('ix_wish_histories_title'), 'wish_histories', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wish_histories_title'), table_name='wish_histories')
    op.drop_column('wish_histories', 'title')
    # ### end Alembic commands ###
