"""Initial active_wish

Revision ID: c2463b7a8c58
Revises: 1e9b4ddffd39
Create Date: 2024-04-01 23:17:15.442746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2463b7a8c58'
down_revision: Union[str, None] = '1e9b4ddffd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
