"""Initial delete wish_history

Revision ID: c47da6fc0640
Revises: a21d3b1456c6
Create Date: 2024-04-01 23:21:45.268670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c47da6fc0640'
down_revision: Union[str, None] = 'a21d3b1456c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wish_history_id', table_name='wish_history')
    op.drop_table('wish_history')
    op.add_column('wishes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wishes', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='foreignkey')
    op.drop_column('wishes', 'owner_id')
    op.create_table('wish_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wish_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fulfilled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], name='wish_history_executor_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wish_history_user_id_fkey'),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], name='wish_history_wish_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wish_history_pkey')
    )
    op.create_index('ix_wish_history_id', 'wish_history', ['id'], unique=False)
    # ### end Alembic commands ###
