"""wishhistory_new

Revision ID: ca6dd5277460
Revises: 7e8abf484167
Create Date: 2024-08-11 19:53:06.002003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6dd5277460'
down_revision: Union[str, None] = '7e8abf484167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wish_histories_wish_id_fkey', 'wish_histories', type_='foreignkey')
    op.drop_column('wish_histories', 'wish_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_histories', sa.Column('wish_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('wish_histories_wish_id_fkey', 'wish_histories', 'wishes', ['wish_id'], ['id'])
    # ### end Alembic commands ###
