version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: wishltbot_app
    command: >
      sh -c "alembic upgrade head &&
             python main.py --host 0.0.0.0 --port 8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      TOKEN: ${TOKEN}
      BOT_NAME: ${BOT_NAME}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      TIME_LIFE_PROMOCODE: ${TIME_LIFE_PROMOCODE}
      TIME_LIFE: ${TIME_LIFE}
      COUNT_WISH: ${COUNT_WISH}
      COUNT_WISH_PREMIUM: ${COUNT_WISH_PREMIUM}
      MAX_WISH_LENGTH: ${MAX_WISH_LENGTH}
      TEST_PERIOD_PREMIUM: ${TEST_PERIOD_PREMIUM}
      TIME_PREMIUM: ${TIME_PREMIUM}
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
